### ISSUE TITLE
bug: needs a minimum version check

### ISSUE THREAD

**Issue by srl295** [RafaelGSS/is-my-node-vulnerable#2]
```shell
$ npx is-my-node-vulnerable
Cannot find module 'node:events'
Require stack:
- /home/pi/.npm/_npx/4770/lib/node_modules/is-my-node-vulnerable/index.js
$ node --version
v12.22.8
```

I guess it's probably vulnerable :)

**Comment by srl295** [comment]
```shell
$ node --version
v8.17.0
$ npx is-my-node-vulnerable
Unexpected token {
```

```shell
$ node --version
v0.12.18
$ is-my-node-vulnerable
const Buffer = require('safe-buffer').Buffer
^^^^^
SyntaxError: Use of const in strict mode.
```

OK ,that's a little out there.

**Comment by RafaelGSS** [comment]
Only active release lines are supported. Maybe we should clarify it in the README.md. Would you mind creating a PR to update it?

**Comment by ljharb** [comment]
Why not support older node versions, so I can get a list of exactly _what_ the version of node is vulnerable to?

**Comment by RafaelGSS** [comment]
Just clarifying if someone takes it before me. We should include a note in the README and support v14.0.0 (pretty much by removing node: prefix)

**Comment by RafaelGSS** [comment]
> Why not support older node versions, so I can get a list of exactly _what_ the version of node is vulnerable to?

The idea is to answer: am I vulnerable if I use v12? Well, if you are using an end-of-life version you are definitely in "DANGER".  Also, to include the support to prior versions we would need to refactor the Node.js Security DB (prior versions are missing CVE or other key information) and honestly, I don't think that's worth the change.

**Comment by ljharb** [comment]
Why am I in danger if there aren't any CVEs, or if the ones that exist don't apply to me?

**Comment by RafaelGSS** [comment]
The simple answer is that we don't validate if non-supported versions are affected by a vulnerability or not. 

For instance, if you open a HackerOne report today saying that v14 is vulnerable and it gets accepted and a security patch is launched. The Security DB will hold the following information:
```
{
  cve: ["X"],
  afectedVersions: ["v14.x"]
}
```

We can't include <= v14.x for the simple reason we don't validate the patch against end-of-life versions, in the end of the day, it's not supported anymore.

**Comment by srl295** [comment]
concrete suggestion:
 - merge #3
 - if there's a version X (12, 14, etc.) before which it's not supported, have an early test, conceptually:

```js
if(process.version.substring(1).split('.')[0] < 14) { console.error('Don't know: this tool needs node >= v14');return; }
```

that would make this super friendly, you could "always" run it (if you had at least v12.0.0).

**Comment by srl295** [comment]
> Why am I in danger if there aren't any CVEs, or if the ones that exist don't apply to me?

This tool could easily just say, "I don't know" if it's too old to give more detail

**Comment by ljharb** [comment]
The existence of a vulnerability is not related to whether the version that's vulnerable is supported or not - that only affects whether it will be fixed.

**Comment by srl295** [comment]
> Only active release lines are supported. 

Ah. A user may not know which those are.  I have to look it up sometimes. It might be helpful to perform that check for the user.

> Maybe we should clarify it in the README.md. Would you mind creating a PR to update it?

If i get a chance, likely…

**Comment by RafaelGSS** [comment]
The point is that after the end-of-life of a version, you don't know if you are in danger or not. Let me elaborate...

v12 is end-of-life and v14.0.0 isn't vulnerable and we are about to release v14.0.1 with a security patch. So, a CVE will be assigned to the v14 version saying basically, _v14.0.0 is vulnerable, please consider upgrading to v14.0.1_.

However, v12 won't receive a CVE or a patch, so nobody knows if the vulnerability reported affects v12 or not. Therefore, this tool is unable to say: you are vulnerable or you aren't vulnerable. You can also guess that if a vulnerability affects v14 it affects v12 too, but not all the cases are like that, so again... we don't know and we will never know.

The safest option is to say: end-of-life versions are vulnerable.

**Comment by ljharb** [comment]
why wouldn't the CVE be assigned to v12? That's not how CVEs work - every vulnerable version, especially ones that won't be fixed, is included in the CVE. Security researchers LOVE hitting the maximum number of versions with their CVEs.

Absolutely it won't receive a patch, but that's unrelated to the vuln itself.

**Comment by RafaelGSS** [comment]
> why wouldn't the CVE be assigned to v12?

Why would it receive a CVE since we didn't validate if that affects v12 or not (cause it's end-of-life)?

**Comment by ljharb** [comment]
Anything that's potentially vulnerable that maintainers *haven't* validated is typically assumed to be vulnerable and included in the CVE.

**Comment by RafaelGSS** [comment]
So this basically confirms my point: If you use an end-of-life version, you are vulnerable. I know that might have a possibility if no security patches were released after the version went to end-of-life you aren't vulnerable, but you know, it's not safe to say "ALL GOOD" and definitely not worth the change (considering we aren't talking about just removing the prefix and including v12 to the matrix test).

**Comment by RafaelGSS** [comment]
One thing we could do instead is: if there's no security release after a version went end-of-life returns ALL GOOD. But, I'd also include a warning to recommend updating anywhere.

An important note is that, just because there's no security patch, it doesn't mean there's no vulnerability. We've received some reports that are VALID but were closed as N/A just because the version is end-of-life.

**Comment by srl295** [comment]
> The Security DB now doesn't provide information for end-of-life versions (v12 in this case). 

Does the DB tell you what the oldest version it includes is? If so, you could test that.

**Comment by srl295** [comment]
https://github.com/nodejs/security-wg/issues/871 relevant here

**Comment by ljharb** [comment]
@srl295 engines' support doesn't affect semver; something going EOL doesn't mean you're allowed to drop support for it without a semver-major.

**Comment by srl295** [comment]
> @srl295 engines' support doesn't affect semver; something going EOL doesn't mean you're allowed to drop support for it without a semver-major.

I'm not sure I follow here.  The vuln database says it only supports actively supported versions, I was going from that.

**Comment by ljharb** [comment]
sure, that's fine, but *this package* (or rather, any package wishing to comply with semver) has to do a semver-major to drop any node version, no matter how EOL it is.
