### ISSUE TITLE
Specify minimum supported Node.js version in package.json engines field

### ISSUE THREAD

**Issue by trivikr** [RafaelGSS/is-my-node-vulnerable#21]
### Is your feature request related to a problem? Please describe.

The minimum supported Node.js version is not specified for `is-my-node-vulnerable` module.

The consumers are not aware of which versions this module supports, and it keep re-appearing
* Example Issues
  * https://github.com/RafaelGSS/is-my-node-vulnerable/issues/2
  * https://github.com/RafaelGSS/is-my-node-vulnerable/issues/19#issuecomment-2425181636
* Twitter: https://x.com/trivikram/status/1848093316627214502

### Describe the solution you'd like

Specify which versions of Node.js the module supports in package.json engines field, and add tests for them in CI.
Since consumers are expected to run this module on EOL versions of Node.js, maybe support one or two EOL LTS versions?

As per the current CI setup, this module is expected to support Node.js 14+
https://github.com/RafaelGSS/is-my-node-vulnerable/blob/050a05a0798054e069bd305e866a84e326bba558/.github/workflows/test.yml#L14

**Comment by RafaelGSS** [comment]
Let's target v14 for now and see what needs to be done to support v12 and v10. Wdyt?

**Comment by RafaelGSS** [comment]
Actually, we could support pretty much all versions if we first check if `process.version < 18.0.0` and throw the EOL warning, before requiring or using any module
