### ISSUE TITLE
Add support to environment check

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/is-my-node-vulnerable#9]
Sometimes a security vulnerability affects only windows or macOS and in order to make this package consistent, a check against the environment should be performed.

Currently, the Node.js Security DB doesn't provide information about the CVE environment, so the steps should be:

1) Update the Security DB to provide this information
2) Update this package

**Comment by UlisesGascon** [comment]
Happy to help if you need an extra hand 😉

**Comment by UlisesGascon** [comment]
Next steps:
- [ ] Add `affectedEnvironments` to the Nodejs Core Vuln model. See: https://github.com/nodejs/security-wg/pull/912
- [ ] Update the vuln DB to include for the core reported vulnerabilities
- [ ] Add business logic to check against the `os.platform()`
